# Generated by Django 2.2.14 on 2021-02-15 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='media/'),
            preserve_default=False,
        ),
    ]
